version: "3.8"
services: 
  real-estate-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    # environment:
    #   - VITE_VERSION=$npm_package_version
    env_file: 
      - ./.env.development