version: "3.8"
services: 
  real-estate-app:
    build: .
    ports:
      - "3000:3000"
    volumes: 
      - .:/app
    # environment:
    #   - REACT_APP_VERSION=$npm_package_version
    env_file: 
      - ./.env.development