FROM node:16.14-buster as build
WORKDIR /app
COPY package.json package.json
RUN npm install 
COPY . .   
RUN npm run build

FROM nginx
COPY ./container/etc/nginx/nginx.template /etc/nginx/config.d/default.conf 
COPY --from=build /app/build /usr/share/nginx/html