name: Deploy to Digital Ocean Droplet

on:
  push:
    branches:
      - "prod"

env:
  NODE_ENV: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v3
      with:
       node-version: ${{ matrix.node-version }}

    - run: npm install --legacy-peer-deps
    - run: npm run build

    - name: Upload artifact in order to deploy
      uses: actions/upload-artifact@v2
      with:
       name: production-files
       path: ./build

  deploy-prod:
    name: Deploy 
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v2
      with:
       name: production-files
       path: ./build

    - name: Send To Server
      uses: appleboy/scp-action@master
      with:
       host: ${{ secrets.HOST }}
       username: root
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       source: ./build/*
       target: /var/www/realestateapi.rafhaelmarques.me/
       overwrite: true

    - name: Restart Nginx
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       username: root
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       script: systemctl restart nginx